language: node_js

node_js:
  - "11.15.0"

services:
  - postgresql

env:
  - TEST_SUITE=unit-tests
  - TEST_SUITE=linter

install:
  - yarn install

before_script:
  - yarn run typeorm migration:run

script:
  - yarn run test:$TEST_SUITE
