language: node_js

node_js:
  - "11.15.0"

services:
  - postgresql

env:
  - DATABASE_URL=postgres://postgres@127.0.0.1:5432/postgres JWT_SECRET_KEY=secret

install:
  - yarn install

before_script:
  - yarn run typeorm migration:run

script:
  - yarn run test --coverage
