#
# This docker-compose file should only be used for development environment,
# using it for production is probably a bad idea
#

version: '3'

services:
  db:
    image: postgres:11.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
      - api_assets:/assets
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      NODE_ENV: "development"
      PORT: 3000
      DB_NAME: postgres
      DB_USER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: password
      JWT_SECRET_KEY: secret
      ASSETS_ROOT_DIR: /assets
      FRONT_END_HOST: "http://localhost:4200"
      EMAIL_FROM: "Perfect Week<perfectweek_2020@labeip.epitech.eu>"

  pg-admin:
    image: dpage/pgadmin4
    ports:
      - 4444:80
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.net
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  db_data:
  api_assets:
