version: '3'

services:
  db:
    image: postgres:11.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  api:
    build: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: password

volumes:
  db_data:
