#
# This docker-compose file should only be used for development environment,
# using it for production is probably a bad idea
#

version: '3'

services:
  db:
    image: postgres:11.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  api:
    build: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_NAME: postgres
      DB_USER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: password
      JWT_SECRET_KEY: secret

volumes:
  db_data:
